### ISSUE TITLE
GitHub Actions to automatically run tests on branch push

### ISSUE THREAD

**Issue by naconnors** [Jim-Hodapp-Coaching/ambi-rs#6]
These GH Actions should both build ambi-rs (debug and release) as well as run tests.

**Comment by jhodapp** [comment]
See example from the [esp32-wroom-rp project](https://github.com/Jim-Hodapp-Coaching/esp32-wroom-rp/actions)

**Comment by AntoniosBarotsis** [comment]
Hello! I stumbled upon this org accidentally and could work on this seeing as how no one has picked it up yet :)

I have been playing around with GA pipelines for a while now (albeit not too long for Rust specifically) so I feel like this should be decently easy, it would be great if you could help me figure out exactly what you want for this issue :)

**Comment by jhodapp** [comment]
Hi @AntoniosBarotsis, for now all we're looking for is a simple GitHub Actions pipeline that can run `cargo build` and ensure this succeeds, and then runs `cargo test` and ensures that these tests pass. As Ambi-rs grows in functionality (we're also looking for new people to get involved in building this project. Are you interested in learning Rust more? We've got a small but growing number of people interested in learning both embedded and web-based Rust projects. I'd be happy to tell you more about the community and project if you're interested?

And thank you for speaking up and volunteering on this issue!

**Comment by AntoniosBarotsis** [comment]
I would love to hear more! Should I join your slack team for that? I can do that later today/tomorrow, same for making a PR for this.

**Comment by jhodapp** [comment]
> I would love to hear more! Should I join your slack team for that? I can do that later today/tomorrow, same for making a PR for this.

Awesome, excited to have you join Tony! If you just fill out this simple questionnaire, it will give me everything I need from you to add you to the Slack group and it will also ask you to agree to our community's code of conduct.
